### PR TITLE
Travel-website-mobile-view

### PR DESCRIPTION
**Pull request by maryamsaye**
Added index.html and styles.css for the mobile view.

### CODE REVIEW

**Review by Devsalmasaeed — CHANGES_REQUESTED** [review]
Hi @maryamsaye ,

Good job so far!
You still need to work on some issues to get your project approved, but you are almost there!

<div style="text-align:center;">
    Remote Collaboration
</div>

### To Highlight 💯
- **Clean code** 👍
- **Good use of Gitflow** 👍
- **Implemented some project requirements** 👍

### Required Changes ♻️

- Adjust the width of the video to fit the content
- Add README 

### Optional Suggestions
Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

**Comment by Xfarouq** [comment]
Please specify is this your mobile view or Desktop View? @maryamsaye

**Comment by maryamsaye** [comment]
Sir it is mobile view I have already specified

**Review by Xfarouq — CHANGES_REQUESTED** [review]
Hi @maryamsaye 

Good job so far!
You still need to work on some issues to get your project approved, but you are almost there!

<div style="text-align:center;">
    Remote Collaboration
</div>

### To Highlight 💯
- **Clean code** 👍
- **Good use of Gitflow** 👍
- **Implemented some project requirements** 👍

### Required Changes ♻️

- Please make your mobile design to be responsive
- The reason i asked if it's mobile or desktop, because your desktop design is very well designed and the mobile isn't

### Optional Suggestions
Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

**Review by Devsalmasaeed — APPROVED** [review]
> Hi @maryamsaye ,
> 
> Your project is complete! There is nothing else to say other than... it's time to merge it!!! Congratulations! 🎉
> 
> Remote Collaboration
> ### Highlights
> * ✅ **Professional Readme**
> * ✅ **Good use of Gitflow**
> * ✅ **UI looks like the Figma design**
> * ✅ **Good use of HTML semantics**
> * ✅ **Professional commit messages**
> * ✅ **Professional PR title**
> * ✅ **Professional PR description**
> 
> ### Optional Suggestions
> Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.
> 
> Cheers and Happy coding! 👏👏👏
> 
> _Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification._

**Pull request merged**
